In [5]:
!pip install requests beautifulsoup4 pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from requests) (2024.12.14)
Requirement already satisfied: soupsieve>1.2 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\samta sakha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://books.toscrape.com/'
response = requests.get(url)
response.encoding = 'utf-8'  #fix encoding

soup = BeautifulSoup(response.text, 'html.parser')
books = soup.find_all('article', class_ = 'product_pod')

data =[]
for book in books:
    title = book.h3.a['title']
    price_raw = book.find('p',class_='price_color').text.strip()
    price = price_raw.replace('£','').replace('A—','')
    availability = book.find('p',class_ = 'instock availability').text.strip()
    rating = book.find('p',class_ = 'star-rating')['class'][1]
    data.append({
        'Title': title,
        'Price (GBP)' : float(price),
        'Availability' : availability,
        'Rating' : rating
    })

df = pd.DataFrame(data)

df.to_csv('books_data.csv', index=False)

df.style.set_properties(**{
    'background-color' : '#f0f8ff',
    'color' : '#000',
    'border-color' : 'gray',
    'border-style' :'solid',
    'border-width' : '1px' ,
    'text-align' : 'left',
    'padding' : '5px'
}).highlight_max(subset=['Price (GBP)'], color='lightgreen') \
  .highlight_min(subset=['Price (GBP)'], color='lightcoral') \
  .set_caption("Book Data from books.toscrape.com")

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd  # ✅ Corrected this line

url = 'https://books.toscrape.com/'
response = requests.get(url)
response.encoding = 'utf-8'  # Fix encoding

soup = BeautifulSoup(response.text, 'html.parser')
books = soup.find_all('article', class_='product_pod')

data = []
for book in books:
    title = book.h3.a['title']
    price_raw = book.find('p', class_='price_color').text.strip()
    price = price_raw.replace('£', '').replace('A—', '')  # You might not need 'A—'
    availability = book.find('p', class_='instock availability').text.strip()
    rating = book.find('p', class_='star-rating')['class'][1]

    data.append({
        'Title': title,
        'Price (GBP)': float(price),
        'Availability': availability,
        'Rating': rating
    })

df = pd.DataFrame(data)

df.to_csv('books_data.csv', index=False)

# Display in Jupyter Notebook (optional)
df.style.set_properties(**{
    'background-color': '#f0f8ff',
    'color': '#000',
    'border-color': 'gray',
    'border-style': 'solid',
    'border-width': '1px',
    'text-align': 'left',
    'padding': '5px'
}).highlight_max(subset=['Price (GBP)'], color='lightgreen') \
  .highlight_min(subset=['Price (GBP)'], color='lightcoral') \
  .set_caption("Book Data from books.toscrape.com")